<?php /* public/flight_correction.php */ ?>
<!doctype html>
<html lang="de">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Flug korrigieren</title>
<link rel="stylesheet" href="app.css">
<link rel="stylesheet" href="correction_ux.css">
<link rel="stylesheet" href="master_data_autocomplete.css">
<link rel="stylesheet" href="external_pilot_form.css">
</head>
<body>
<h1>Flug korrigieren</h1>
<div class="nav"><a href="#" onclick="backList();return false;">Zurück zu Flugfreigaben</a></div>
<div class="card"><div class="row"><label>Datum <input id="date" type="date"></label><label>Benutzer <input id="user" value="demo"></label></div></div>
<div class="card correction-card"><h2>Flug korrigieren</h2><div class="row correction-layout"><div class="col leftcol correction-col"><h3>Segelflug</h3><div class="form-line"><label>Segelflugzeug</label><input id="glider"></div><div class="form-line"><label>Segelflugpilot</label><input id="pilot"></div><div class="form-line"><label>Begleiter / FI</label><input id="att"></div><div class="form-line"><label>Startzeit</label><input id="takeoff" type="time"></div><div class="form-line"><label>Landung Segelflugzeug</label><input id="gliderlanding" type="time"></div><div class="form-line"><label>Flugart</label><select id="ft"></select></div><div class="form-line"><label>Abrechnung</label><select id="charge"></select></div><div class="form-line form-line-full"><label>Kommentar</label><textarea id="comment"></textarea></div></div><div class="col rightcol correction-col"><h3>Motorflug</h3><div class="form-line"><label>Motorflugzeug</label><input id="plane"></div><div class="form-line"><label>Motorpilot</label><input id="towpilot"></div><div class="form-line"><label>Startzeit</label><input id="takeoffMirror" type="time"></div><div class="form-line"><label>Landung Motorflugzeug</label><input id="towlanding" type="time"></div><div class="timebox" id="calc"></div><div class="form-line form-line-full"><label>Kommentar</label><textarea id="towcomment"></textarea></div></div></div><div class="missing candidates-box"><h3>Mögliche Gegen-Flüge</h3><p class="small">Bei getrennten kTrax-Operationen kann hier ein Gegenflug ausgewählt und zusammengeführt werden.</p><div class="form-line"><label>Zusammenführen mit Kandidat</label><select id="merge"><option value="">Nicht zusammenführen</option></select></div></div><div class="row action-row action-row-bottom"><button class="ok" onclick="saveCorrection()">Speichern</button><button class="secondary" onclick="backList();return false;">Abbrechen</button></div></div>
<script>
function qs(id){return document.getElementById(id)}function getParam(n,f){const p=new URLSearchParams(location.search);return p.get(n)||f}function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}function timeOnly(v){if(!v)return '';return String(v).replace('T',' ').slice(11,16)}function backQuery(){let p=new URLSearchParams(location.search);return 'from='+(p.get('from')||p.get('date')||'')+'&to='+(p.get('to')||p.get('from')||p.get('date')||'')+'&status='+(p.get('status')||'pending')+'&user='+(p.get('user')||'demo')}function backList(op){location.href='flight_approvals.php?'+backQuery()+(op?'#op-'+op:'')}function mins(a,b){if(!a||!b)return '';let [ah,am]=a.split(':').map(Number),[bh,bm]=b.split(':').map(Number);let m=bh*60+bm-ah*60-am;return m>=0?m:''}function addMin(t,m){if(!t||!m)return '';let [h,mi]=t.split(':').map(Number);let x=h*60+mi+parseInt(m,10);return String(Math.floor(x/60)%24).padStart(2,'0')+':'+String(x%60).padStart(2,'0')}function mark(id,on){let el=qs(id);if(el)el.classList.toggle('req',!!on)}
let opId=parseInt(getParam('operation_id','0'),10);let data=null;
async function loadLists(){let f=await (await fetch('../src/api_flight_types.php?category=glider')).json();qs('ft').innerHTML='<option value="">Bitte wählen</option>'+(f.flight_types||[]).map(x=>`<option value="${esc(x.id)}">${esc(x.code)} - ${esc(x.name)}</option>`).join('');let c=await (await fetch('../src/api_charge_modes.php?context=glider')).json();qs('charge').innerHTML=(c.charge_modes||[]).map(x=>`<option value="${esc(x.id)}" ${String(x.id)==='2'?'selected':''}>${esc(x.display_name||x.name)}</option>`).join('')}
function calc(){qs('calc').innerHTML='Motorflugzeit: '+(mins(qs('takeoff').value,qs('towlanding').value)||'')+' min<br>Segelflugzeit: '+(mins(qs('takeoff').value,qs('gliderlanding').value)||'')+' min'}function syncStart(src){qs('takeoff').value=src.value;qs('takeoffMirror').value=src.value;calc()}
async function loadData(){await loadLists();data=await (await fetch('../src/api_get_operation_for_correction.php?operation_id='+opId)).json();if(!data.ok){alert(data.error||'Fehler');return}let o=data.operation,g=data.glider_entry,t=data.tow_charge||data.towplane_own;qs('date').value=o.operation_date;qs('user').value=getParam('user','demo');if(g){qs('glider').value=g.callsign||'';qs('pilot').value=g.pilot_name||'';qs('att').value=g.attendant_name||'';qs('takeoff').value=timeOnly(g.departure_time);qs('takeoffMirror').value=timeOnly(g.departure_time);qs('gliderlanding').value=timeOnly(g.arrival_time);qs('ft').value=g.vf_flight_type_id||'';qs('charge').value=g.charge_mode||2;qs('comment').value='Korrigiert: Segelflugdaten aktualisiert'}else{qs('takeoff').value=o.takeoff_time||'';qs('takeoffMirror').value=o.takeoff_time||'';qs('glider').value=o.glider_callsign||''}if(t){qs('plane').value=t.tow_callsign||t.callsign||'';qs('towpilot').value=t.tow_pilot_name||'';if(!qs('takeoff').value){qs('takeoff').value=timeOnly(t.departure_time);qs('takeoffMirror').value=timeOnly(t.departure_time)}qs('towlanding').value=timeOnly(t.arrival_time)||(t.tow_minutes&&t.departure_time?addMin(timeOnly(t.departure_time),t.tow_minutes):'');qs('towcomment').value='Korrigiert: Motorflug/Schleppdaten aktualisiert'}else{qs('plane').value=o.tow_callsign||''}let opts='<option value="">Nicht zusammenführen</option>';(data.candidate_motors||[]).forEach(x=>opts+=`<option value="${esc(x.operation_id)}">Motor ${esc(x.callsign)} ${esc(timeOnly(x.departure_time))}</option>`);(data.candidate_gliders||[]).forEach(x=>opts+=`<option value="${esc(x.operation_id)}">Segler ${esc(x.callsign)} ${esc(timeOnly(x.departure_time))}</option>`);qs('merge').innerHTML=opts;calc()}
['takeoff','takeoffMirror'].forEach(id=>setTimeout(()=>qs(id)?.addEventListener('input',e=>syncStart(e.target)),0));['towlanding','gliderlanding'].forEach(id=>setTimeout(()=>qs(id)?.addEventListener('input',calc),0));
function sideWanted(ids){return ids.some(id=>qs(id)&&qs(id).value)}
async function saveCorrection(){['date','glider','pilot','takeoff','gliderlanding','ft','charge','plane','towpilot','towlanding'].forEach(id=>mark(id,false));let errors=[];let gliderWanted=sideWanted(['glider','pilot','gliderlanding','ft','charge']);let motorWanted=sideWanted(['plane','towpilot','towlanding']);if(!qs('date').value){mark('date',true);errors.push('Datum fehlt')}if(!gliderWanted&&!motorWanted)errors.push('Segelflug- oder Motorflugdaten fehlen');if(gliderWanted){[['glider','Segelflugzeug fehlt'],['pilot','Segelflugpilot fehlt'],['takeoff','Startzeit fehlt'],['gliderlanding','Landung Segelflugzeug fehlt'],['ft','Flugart Segelflug fehlt'],['charge','Abrechnungsart fehlt']].forEach(x=>{if(!qs(x[0]).value){mark(x[0],true);errors.push(x[1])}})}if(motorWanted){[['plane','Motorflugzeug fehlt'],['towpilot','Motorpilot fehlt'],['takeoff','Startzeit fehlt'],['towlanding','Landung Motorflugzeug fehlt']].forEach(x=>{if(!qs(x[0]).value){mark(x[0],true);errors.push(x[1])}})}if(gliderWanted&&qs('gliderlanding').value&&qs('takeoff').value&&qs('gliderlanding').value<qs('takeoff').value){mark('gliderlanding',true);errors.push('Landung Segelflugzeug darf nicht vor Startzeit liegen')}if(motorWanted&&qs('towlanding').value&&qs('takeoff').value&&qs('towlanding').value<qs('takeoff').value){mark('towlanding',true);errors.push('Landung Motorflugzeug darf nicht vor Startzeit liegen')}if(errors.length){alert('Speichern nicht möglich.\n\nBitte ausfüllen/korrigieren:\n- '+[...new Set(errors)].join('\n- '));return}let payload={operation_id:opId,date:qs('date').value,user:qs('user').value,glider_callsign:qs('glider').value,pilot_name:qs('pilot').value,attendant_name:qs('att').value,tow_callsign:qs('plane').value,tow_pilot_name:qs('towpilot').value,takeoff_time:qs('takeoff').value,tow_landing_time:qs('towlanding').value,glider_landing_time:qs('gliderlanding').value,vf_flight_type_id:qs('ft').value,charge_mode:qs('charge').value,comment:qs('comment').value,tow_comment:qs('towcomment').value,merge_operation_id:qs('merge').value};let r=await (await fetch('../src/api_save_operation_correction.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)})).json();if(!r.ok){alert(r.error||'Fehler');return}backList(r.operation_id)}
loadData();
</script><script src="i18n.js"></script>
<script src="master_data_autocomplete.js"></script>
</body></html>
