<?php
declare(strict_types=1);require_once __DIR__.'/../src/auth.php';require_once __DIR__.'/../src/permissions.php';$user=auth_require_login();require_role('ADMIN');?>
<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>VF-Kontakttransfer</title><link rel="stylesheet" href="app.css"></head><body>
<div class="card"><div class="row"><div><strong>Angemeldet:</strong> <?=htmlspecialchars((string)$user['display_name'],ENT_QUOTES,'UTF-8')?></div><div><a class="button secondary" href="dashboard.php">Dashboard</a></div><div><a class="button secondary" href="logout.php">Logout</a></div></div></div><h1>Externe Kontakte zu Vereinsflieger</h1><p class="info">Neue oder geänderte Kontakte werden als ausstehend geführt. Nach dem CSV-Download bleibt eine manuelle Bestätigung mit der VF-Benutzernummer erforderlich.</p><div class="card"><div class="row"><div><b id="pendingCount">0</b><br>Ausstehend</div><div><b id="downloadedCount">0</b><br>CSV heruntergeladen</div><div><b id="linkedCount">0</b><br>Verknüpft</div></div><p><a class="button ok" href="../src/export_vf_members_csv.php">Ausstehende Kontakte als VF-CSV herunterladen</a></p></div><div class="card"><h2>Kontakte</h2><div id="contacts">Laden...</div></div>
<script>
const csrf=<?=json_encode(csrf_token(),JSON_UNESCAPED_SLASHES)?>;const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
async function jsonResponse(r){const text=await r.text();try{return JSON.parse(text)}catch(e){throw new Error(`API liefert kein JSON (HTTP ${r.status}). Antwortanfang: ${text.slice(0,160)}`)}}
async function load(){const r=await fetch('../src/api_vf_external_contacts.php',{credentials:'same-origin'}),j=await jsonResponse(r);if(!r.ok||!j.ok)throw new Error(j.error||`HTTP ${r.status}`);const c={pending:0,downloaded:0,linked:0};j.items.forEach(x=>c[x.vf_status]++);pendingCount.textContent=c.pending;downloadedCount.textContent=c.downloaded;linkedCount.textContent=c.linked;let h='<table><tr><th>Name</th><th>E-Mail</th><th>Telefon</th><th>Status</th><th>VF-Benutzernr.</th><th>Aktion</th></tr>';for(const x of j.items){h+=`<tr><td>${esc(x.name)}</td><td>${esc(x.email)}</td><td>${esc(x.phone)}</td><td>${esc({pending:'Ausstehend',downloaded:'CSV heruntergeladen',linked:'Verknüpft'}[x.vf_status]||x.vf_status)}</td><td>${esc(x.vf_user_no||'')}</td><td>`;if(x.vf_status==='downloaded')h+=`<input id="vf_${x.id}" size="12" placeholder="VF-Nr."> <button onclick="act(${x.id},'mark_linked')">Verknüpft</button> `;if(x.vf_status!=='pending')h+=`<button class="warn" onclick="act(${x.id},'reset_pending')">Erneut exportieren</button>`;h+='</td></tr>'}contacts.innerHTML=h+'</table>'}
async function act(id,action){const body={id,action,csrf_token:csrf};if(action==='mark_linked')body.vf_user_no=document.getElementById('vf_'+id).value.trim();const r=await fetch('../src/api_vf_external_contacts.php',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify(body)});let j;try{j=await jsonResponse(r)}catch(e){alert(e.message);return}if(!r.ok||!j.ok){alert(j.error||`HTTP ${r.status}`);return}await load()}load().catch(e=>contacts.innerHTML='<p class="warnbox">'+esc(e.message)+'</p>');
</script></body></html>
