<?php
declare(strict_types=1);
namespace LSZJ\Vereinsflieger;
use PDO;use RuntimeException;use Throwable;
final class ManualFlightSyncService {
 public function __construct(private PDO $pdo,private FlightEditPreviewService $previews,private FlightSyncBaselineService $baselines,private FlightPayloadComparator $comparator){}
 public function preview(int $entryId,int $actorId):array {$p=$this->previews->preview($entryId,$actorId);return $p+['rest_calls'=>0,'allowed_kinds'=>['manual_edit','billing_replacement']];}
 public function complete(int $entryId,int $actorId,int $expectedVersion,string $expectedHash,string $kind,int $activeFlid,string $reason,bool $vfChecked,bool $confirmed,string $notes=''):array {
  if(!$vfChecked||!$confirmed)throw new RuntimeException('Manuelle VF-Pruefung und Abschlussbestaetigung sind Pflicht.');if(!in_array($kind,['manual_edit','billing_replacement'],true))throw new RuntimeException('Ungueltige Synchronisationsart.');$reason=$this->validateText($reason,'Korrekturgrund');$notes=trim($notes);if($activeFlid<=0)throw new RuntimeException('Aktive VF-flid ist ungueltig.');
  $this->pdo->beginTransaction();try{$entry=$this->lockEntry($entryId);if(!$entry)throw new RuntimeException('Buchung nicht gefunden.');if((int)$entry['row_version']!==$expectedVersion)throw new RuntimeException('Der Flug wurde nach der Vorschau erneut veraendert.');$p=$this->previews->preview($entryId,$actorId);if(!hash_equals($p['current_payload_hash'],$expectedHash))throw new RuntimeException('Der Payload wurde nach der Vorschau erneut veraendert.');$original=(int)$p['vf_flid'];if($kind==='manual_edit'&&$activeFlid!==$original)throw new RuntimeException('Bei manual_edit muss die VF-flid unveraendert bleiben.');if($kind==='billing_replacement'&&$activeFlid===$original)throw new RuntimeException('Beim Ersatzflug muss eine neue VF-flid angegeben werden.');$this->assertFlidAvailable($entryId,$activeFlid,$kind);
   $run=$this->insertRun($p,$kind,$original,$activeFlid,$reason,$actorId,$notes);$source=$kind;$snapshot=$this->recordSnapshot($entryId,(int)$p['operation_id'],$activeFlid,$source,$run,$p['current_payload'],$actorId);$u=$this->pdo->prepare("UPDATE accounting_entries SET vf_sync_status='in_sync',vf_sync_checked_at=NOW() WHERE id=?");$u->execute([$entryId]);$this->pdo->commit();return ['ok'=>true,'status'=>'completed','manual_sync_run_id'=>$run,'snapshot_id'=>$snapshot,'sync_kind'=>$kind,'original_vf_flid'=>$original,'active_vf_flid'=>$activeFlid,'rest_calls'=>0];
  }catch(Throwable $e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw $e;}
 }
 private function lockEntry(int $id):array|false {$s=$this->pdo->prepare('SELECT * FROM accounting_entries WHERE id=? FOR UPDATE');$s->execute([$id]);return $s->fetch(PDO::FETCH_ASSOC);}
 private function assertFlidAvailable(int $entryId,int $flid,string $kind):void {if($kind!=='billing_replacement')return;$s=$this->pdo->prepare('SELECT 1 FROM vf_flight_sync_snapshots WHERE vf_flid=? AND accounting_entry_id<>? LIMIT 1');$s->execute([$flid,$entryId]);if($s->fetchColumn())throw new RuntimeException('Die neue VF-flid ist bereits einem anderen LSZJ-Flug zugeordnet.');}
 private function insertRun(array $p,string $kind,int $old,int $active,string $reason,int $actor,string $notes):int {$s=$this->pdo->prepare("INSERT INTO vf_manual_sync_runs(sync_token,accounting_entry_id,operation_id,vf_flight_export_id,vf_flight_change_check_id,vf_flight_local_change_id,original_vf_flid,active_vf_flid,row_version,sync_kind,status,billing_status,old_payload_hash,confirmed_payload_hash,old_payload_json,confirmed_payload_json,differences_json,correction_reason,vf_checked_by,vf_checked_at,confirmed_by,notes) VALUES(?,?,?,?,?,?,?,?,?,?,'completed',?,?,?,?,?,?,?,?,NOW(),?,?)");$s->execute([bin2hex(random_bytes(32)),$p['accounting_entry_id'],$p['operation_id'],$p['vf_flight_export_id'],$p['change_check_id'],$p['local_change_id'],$old,$active,$p['row_version'],$kind,$kind==='billing_replacement'?'invoiced_replaced':'not_invoiced',$p['baseline']['payload_hash'],$p['current_payload_hash'],$this->json($p['baseline']['payload']),$this->json($p['current_payload']),$this->json($p['differences']),$reason,$actor,$actor,$notes===''?null:$notes]);return (int)$this->pdo->lastInsertId();}
 private function recordSnapshot(int $entryId,int $operationId,int $flid,string $source,int $runId,array $payload,int $actor):int {$s=$this->pdo->prepare('INSERT INTO vf_flight_sync_snapshots(accounting_entry_id,operation_id,vf_flid,source,source_record_id,payload_hash,payload_json,created_by) VALUES(?,?,?,?,?,?,?,?)');$s->execute([$entryId,$operationId,$flid,$source,$runId,$this->comparator->hash($payload),$this->json($payload),$actor]);return (int)$this->pdo->lastInsertId();}
 private function validateText(string $v,string $name):string {$v=trim($v);$n=function_exists('mb_strlen')?mb_strlen($v,'UTF-8'):strlen($v);if($n<5||$n>1000)throw new RuntimeException($name.' muss 5 bis 1000 Zeichen enthalten.');return $v;}
 private function json(mixed $v):string{return json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);}
}
