-- Dashboard-Übersetzungen und Korrektur gemischter DE/FR-Texte
SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;

INSERT INTO i18n_translations (translation_key, lang, translation_text) VALUES
('Administrator', 'de', 'Administrator'),
('Administrator', 'fr', 'Administrateur'),
('Aktiver Flugdienstleiter:', 'de', 'Aktiver Flugdienstleiter:'),
('Aktiver Flugdienstleiter:', 'fr', 'Chef de service de vol actif :'),
('Alle Flüge freigeben', 'de', 'Alle Flüge freigeben'),
('Alle Flüge freigeben', 'fr', 'Valider tous les vols'),
('Angemeldet:', 'de', 'Angemeldet:'),
('Angemeldet:', 'fr', 'Connecté :'),
('Benutzer, Stammdaten und den Personenabgleich mit Vereinsflieger verwalten.', 'de', 'Benutzer, Stammdaten und den Personenabgleich mit Vereinsflieger verwalten.'),
('Benutzer, Stammdaten und den Personenabgleich mit Vereinsflieger verwalten.', 'fr', 'Gérer les utilisateurs, les données de base et le rapprochement des personnes avec Vereinsflieger.'),
('Betriebstag abschliessen und für VF freigeben', 'de', 'Betriebstag abschliessen und für VF freigeben'),
('Betriebstag abschliessen und für VF freigeben', 'fr', 'Clôturer la journée d’exploitation et la valider pour VF'),
('C4-Tagesexport nach VF', 'de', 'C4-Tagesexport nach VF'),
('C4-Tagesexport nach VF', 'fr', 'Export journalier C4 vers VF'),
('C4-Tagesexport öffnen', 'de', 'C4-Tagesexport öffnen'),
('C4-Tagesexport öffnen', 'fr', 'Ouvrir l’export journalier C4'),
('CSV-Stammdatenimport', 'de', 'CSV-Stammdatenimport'),
('CSV-Stammdatenimport', 'fr', 'Import CSV des données de base'),
('Chef de service de voldienst', 'de', 'Chef de service de voldienst'),
('Chef de service de voldienst', 'fr', 'Service de chef de vol'),
('Clôture journalière Check de service de vol', 'de', 'Clôture journalière Check de service de vol'),
('Clôture journalière Check de service de vol', 'fr', 'Clôture journalière du chef de service de vol'),
('Correctionen exportierter Flüge', 'de', 'Correctionen exportierter Flüge'),
('Correctionen exportierter Flüge', 'fr', 'Corrections des vols exportés'),
('D1-Änderungsliste', 'de', 'D1-Änderungsliste'),
('D1-Änderungsliste', 'fr', 'Liste des modifications D1'),
('Der Betriebstag wird erst nach vollständiger Prüfung und Freigabe aller Flüge abgeschlossen. Der Abschluss gibt die Tagesdaten für den Export nach Vereinsflieger frei.', 'de', 'Der Betriebstag wird erst nach vollständiger Prüfung und Freigabe aller Flüge abgeschlossen. Der Abschluss gibt die Tagesdaten für den Export nach Vereinsflieger frei.'),
('Der Betriebstag wird erst nach vollständiger Prüfung und Freigabe aller Flüge abgeschlossen. Der Abschluss gibt die Tagesdaten für den Export nach Vereinsflieger frei.', 'fr', 'La journée d’exploitation n’est clôturée qu’après le contrôle complet et la validation de tous les vols. La clôture libère les données du jour pour l’export vers Vereinsflieger.'),
('Der Flugdienstleiterdienst ist derzeit nicht besetzt.', 'de', 'Der Flugdienstleiterdienst ist derzeit nicht besetzt.'),
('Der Flugdienstleiterdienst ist derzeit nicht besetzt.', 'fr', 'Le service de chef de vol n’est actuellement pas assuré.'),
('Dienst übernehmen', 'de', 'Dienst übernehmen'),
('Dienst übernehmen', 'fr', 'Prendre le service'),
('Exportjournal', 'de', 'Exportjournal'),
('Exportjournal', 'fr', 'Journal des exports'),
('Flugbetrieb', 'de', 'Flugbetrieb'),
('Flugbetrieb', 'fr', 'Opérations de vol'),
('Flugdaten kontrollieren', 'de', 'Flugdaten kontrollieren'),
('Flugdaten kontrollieren', 'fr', 'Contrôler les données de vol'),
('Flugdienstleiterdienst', 'de', 'Flugdienstleiterdienst'),
('Flugdienstleiterdienst', 'fr', 'Service de chef de vol'),
('Flüge prüfen, freigeben und bei Bedarf manuell erfassen.', 'de', 'Flüge prüfen, freigeben und bei Bedarf manuell erfassen.'),
('Flüge prüfen, freigeben und bei Bedarf manuell erfassen.', 'fr', 'Contrôler et valider les vols, et les saisir manuellement si nécessaire.'),
('Im Pilotbetrieb führt ein Administrator den Export nach jedem abgeschlossenen Flugtag manuell aus.', 'de', 'Im Pilotbetrieb führt ein Administrator den Export nach jedem abgeschlossenen Flugtag manuell aus.'),
('Im Pilotbetrieb führt ein Administrator den Export nach jedem abgeschlossenen Flugtag manuell aus.', 'fr', 'Pendant la phase pilote, un administrateur effectue manuellement l’export après chaque journée de vol clôturée.'),
('Kein Flugdienstleiter aktiv', 'de', 'Kein Flugdienstleiter aktiv'),
('Kein Flugdienstleiter aktiv', 'fr', 'Aucun chef de service de vol actif'),
('Korrekturen exportierter Flüge', 'de', 'Korrekturen exportierter Flüge'),
('Korrekturen exportierter Flüge', 'fr', 'Corrections des vols exportés'),
('LSZJ Dashboard', 'de', 'LSZJ Dashboard'),
('LSZJ Dashboard', 'fr', 'Tableau de bord LSZJ'),
('Logout', 'de', 'Logout'),
('Logout', 'fr', 'Se déconnecter'),
('Lokale Korrekturen und die manuelle Abstimmung mit VF werden revisionssicher geführt.', 'de', 'Lokale Korrekturen und die manuelle Abstimmung mit VF werden revisionssicher geführt.'),
('Lokale Korrekturen und die manuelle Abstimmung mit VF werden revisionssicher geführt.', 'fr', 'Les corrections locales et la synchronisation manuelle avec VF sont consignées de manière traçable.'),
('Manuelle VF-Synchronisation', 'de', 'Manuelle VF-Synchronisation'),
('Manuelle VF-Synchronisation', 'fr', 'Synchronisation manuelle avec VF'),
('Personen aus VF synchronisieren', 'de', 'Personen aus VF synchronisieren'),
('Personen aus VF synchronisieren', 'fr', 'Synchroniser les personnes depuis VF'),
('Pilot', 'de', 'Pilot'),
('Pilot', 'fr', 'Pilote'),
('Seit', 'de', 'Seit'),
('Seit', 'fr', 'Depuis'),
('Tagesabschluss Flugdienstleiter', 'de', 'Tagesabschluss Flugdienstleiter'),
('Tagesabschluss Flugdienstleiter', 'fr', 'Clôture journalière du chef de service de vol'),
('Tagesabschluss öffnen', 'de', 'Tagesabschluss öffnen'),
('Tagesabschluss öffnen', 'fr', 'Ouvrir la clôture journalière'),
('Tagesabschlussprüfung auf Grün bringen', 'de', 'Tagesabschlussprüfung auf Grün bringen'),
('Tagesabschlussprüfung auf Grün bringen', 'fr', 'Faire passer le contrôle de clôture journalière au vert'),
('Uhr', 'de', 'Uhr'),
('Uhr', 'fr', 'h'),
('Utilisateur, Stammdaten und den Personenabgleich mit Vereinsflieger verwalten.', 'de', 'Utilisateur, Stammdaten und den Personenabgleich mit Vereinsflieger verwalten.'),
('Utilisateur, Stammdaten und den Personenabgleich mit Vereinsflieger verwalten.', 'fr', 'Gérer les utilisateurs, les données de base et le rapprochement des personnes avec Vereinsflieger.')
ON DUPLICATE KEY UPDATE translation_text = VALUES(translation_text);
