-- Korrektur der französischen Flugfreigaben und beschädigter Altwerte
SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;

-- Frühere fehlerhafte PowerShell-Pipelines erzeugten Schlüssel/Werte mit ?? .
-- Echte UI-Fragen enthalten höchstens ein einzelnes Fragezeichen.
DELETE FROM i18n_translations
WHERE translation_key LIKE '%??%'
   OR translation_text LIKE '%??%';

INSERT INTO i18n_translations (translation_key, lang, translation_text) VALUES
('+ Flug manuell erfassen', 'de', '+ Flug manuell erfassen'),
('+ Flug manuell erfassen', 'fr', '+ Saisir un vol manuellement'),
('Alle', 'de', 'Alle'),
('Alle', 'fr', 'Tous'),
('Benutzerverwaltung', 'de', 'Benutzerverwaltung'),
('Benutzerverwaltung', 'fr', 'Gestion des utilisateurs'),
('Bereits nach Vereinsflieger exportiert, schreibgeschützt.', 'de', 'Bereits nach Vereinsflieger exportiert, schreibgeschützt.'),
('Bereits nach Vereinsflieger exportiert, schreibgeschützt.', 'fr', 'Déjà exporté vers Vereinsflieger, en lecture seule.'),
('Bis', 'de', 'Bis'),
('Bis', 'fr', 'Au'),
('D1-Änderungsliste', 'de', 'D1-Änderungsliste'),
('D1-Änderungsliste', 'fr', 'Liste des modifications D1'),
('Dashboard', 'de', 'Dashboard'),
('Dashboard', 'fr', 'Tableau de bord'),
('Flug korrigieren', 'de', 'Flug korrigieren'),
('Flug korrigieren', 'fr', 'Corriger le vol'),
('Flugdienstleiter', 'de', 'Flugdienstleiter'),
('Flugdienstleiter', 'fr', 'Chef de service de vol'),
('Flugfreigaben', 'de', 'Flugfreigaben'),
('Flugfreigaben', 'fr', 'Validations des vols'),
('Gestern', 'de', 'Gestern'),
('Gestern', 'fr', 'Hier'),
('Heute', 'de', 'Heute'),
('Heute', 'fr', 'Aujourd’hui'),
('Kein Motorflug/Schlepp vorhanden.', 'de', 'Kein Motorflug/Schlepp vorhanden.'),
('Kein Motorflug/Schlepp vorhanden.', 'fr', 'Aucun vol moteur/remorquage disponible.'),
('Kein Segelflug zu diesem Motorflug vorhanden.', 'de', 'Kein Segelflug zu diesem Motorflug vorhanden.'),
('Kein Segelflug zu diesem Motorflug vorhanden.', 'fr', 'Aucun vol en planeur correspondant à ce vol moteur.'),
('Keine Einträge im aktuellen Filter.', 'de', 'Keine Einträge im aktuellen Filter.'),
('Keine Einträge im aktuellen Filter.', 'fr', 'Aucune entrée dans le filtre actuel.'),
('Korrektur', 'de', 'Korrektur'),
('Korrektur', 'fr', 'Correction'),
('Laden', 'de', 'Laden'),
('Laden', 'fr', 'Charger'),
('Letzte 7 Tage', 'de', 'Letzte 7 Tage'),
('Letzte 7 Tage', 'fr', '7 derniers jours'),
('Motorflug löschen', 'de', 'Motorflug löschen'),
('Motorflug löschen', 'fr', 'Supprimer le vol moteur'),
('Operation', 'de', 'Operation'),
('Operation', 'fr', 'Opération'),
('Schlepp zu Segelflug erfassen', 'de', 'Schlepp zu Segelflug erfassen'),
('Schlepp zu Segelflug erfassen', 'fr', 'Saisir le remorquage pour le vol en planeur'),
('Segelflug löschen', 'de', 'Segelflug löschen'),
('Segelflug löschen', 'fr', 'Supprimer le vol en planeur'),
('Segelflug zu Schleppflug erfassen', 'de', 'Segelflug zu Schleppflug erfassen'),
('Segelflug zu Schleppflug erfassen', 'fr', 'Saisir le vol en planeur pour le vol de remorquage'),
('Speichern & Freigeben', 'de', 'Speichern & Freigeben'),
('Speichern & Freigeben', 'fr', 'Enregistrer et valider'),
('Status', 'de', 'Status'),
('Status', 'fr', 'Statut'),
('Von', 'de', 'Von'),
('Von', 'fr', 'Du'),
('Zeitraum:', 'de', 'Zeitraum:'),
('Zeitraum:', 'fr', 'Période :'),
('all', 'de', 'all'),
('all', 'fr', 'Tous'),
('approved', 'de', 'approved'),
('approved', 'fr', 'Validé'),
('bis', 'de', 'bis'),
('bis', 'fr', 'au'),
('correction_required', 'de', 'correction_required'),
('correction_required', 'fr', 'Correction requise'),
('exported', 'de', 'exported'),
('exported', 'fr', 'Exporté'),
('kTrax-Import', 'de', 'kTrax-Import'),
('kTrax-Import', 'fr', 'Import kTrax'),
('pending', 'de', 'pending'),
('pending', 'fr', 'Ouvert'),
('Änderungen, Korrekturen und Löschungen sind in der Flugfreigabemaske nicht mehr möglich.', 'de', 'Änderungen, Korrekturen und Löschungen sind in der Flugfreigabemaske nicht mehr möglich.'),
('Änderungen, Korrekturen und Löschungen sind in der Flugfreigabemaske nicht mehr möglich.', 'fr', 'Les modifications, corrections et suppressions ne sont plus possibles dans l’écran de validation des vols.')
ON DUPLICATE KEY UPDATE translation_text = VALUES(translation_text);
