-- Vollständiger i18n-Ergänzungslauf für sichtbare UI-Texte, technische Werte und Systemmeldungen
SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;

INSERT INTO i18n_translations (translation_key, lang, translation_text) VALUES
('+ Flug manuell erfassen', 'de', '+ Flug manuell erfassen'),
('+ Flug manuell erfassen', 'fr', '+ Saisir un vol manuellement'),
('Abbrechen', 'de', 'Abbrechen'),
('Abbrechen', 'fr', 'Annuler'),
('Abmelden', 'de', 'Abmelden'),
('Abmelden', 'fr', 'Se déconnecter'),
('Abrechnung', 'de', 'Abrechnung'),
('Abrechnung', 'fr', 'Facturation'),
('Abstimmung', 'de', 'Abstimmung'),
('Abstimmung', 'fr', 'Rapprochement'),
('Abstimmung erforderlich', 'de', 'Abstimmung erforderlich'),
('Abstimmung erforderlich', 'fr', 'Rapprochement requis'),
('Administration', 'de', 'Administration'),
('Administration', 'fr', 'Administration'),
('Administrativ beenden', 'de', 'Administrativ beenden'),
('Administrativ beenden', 'fr', 'Clôturer administrativement'),
('Administrator', 'de', 'Administrator'),
('Administrator', 'fr', 'Administrateur'),
('Administratorrolle erforderlich.', 'de', 'Administratorrolle erforderlich.'),
('Administratorrolle erforderlich.', 'fr', 'Rôle administrateur requis.'),
('Aktiv', 'de', 'Aktiv'),
('Aktiv', 'fr', 'Actif'),
('Aktiver Flugdienstleiter:', 'de', 'Aktiver Flugdienstleiter:'),
('Aktiver Flugdienstleiter:', 'fr', 'Chef de service de vol actif :'),
('all', 'de', 'all'),
('all', 'fr', 'Tous'),
('Alle', 'de', 'Alle'),
('Alle', 'fr', 'Tous'),
('Alle bekannten Piloten anzeigen', 'de', 'Alle bekannten Piloten anzeigen'),
('Alle bekannten Piloten anzeigen', 'fr', 'Afficher tous les pilotes connus'),
('Alle Flüge sind freigegeben oder bereits exportiert.', 'de', 'Alle Flüge sind freigegeben oder bereits exportiert.'),
('Alle Flüge sind freigegeben oder bereits exportiert.', 'fr', 'Tous les vols sont validés ou déjà exportés.'),
('Alle gestarteten Flüge besitzen eine Landung.', 'de', 'Alle gestarteten Flüge besitzen eine Landung.'),
('Alle gestarteten Flüge besitzen eine Landung.', 'fr', 'Tous les vols commencés possèdent un atterrissage.'),
('Angemeldet:', 'de', 'Angemeldet:'),
('Angemeldet:', 'fr', 'Connecté :'),
('Anmelden', 'de', 'Anmelden'),
('Anmelden', 'fr', 'Se connecter'),
('Anmeldung erforderlich.', 'de', 'Anmeldung erforderlich.'),
('Anmeldung erforderlich.', 'fr', 'Connexion requise.'),
('approved', 'de', 'approved'),
('approved', 'fr', 'Validé'),
('Bearbeiten', 'de', 'Bearbeiten'),
('Bearbeiten', 'fr', 'Modifier'),
('Begleiter', 'de', 'Begleiter'),
('Begleiter', 'fr', 'Accompagnant'),
('Begleiter / FI', 'de', 'Begleiter / FI'),
('Begleiter / FI', 'fr', 'Accompagnant / FI'),
('Benutzer', 'de', 'Benutzer'),
('Benutzer', 'fr', 'Utilisateur'),
('Benutzer nicht gefunden.', 'de', 'Benutzer nicht gefunden.'),
('Benutzer nicht gefunden.', 'fr', 'Utilisateur introuvable.'),
('Benutzer und Rollen wurden gespeichert.', 'de', 'Benutzer und Rollen wurden gespeichert.'),
('Benutzer und Rollen wurden gespeichert.', 'fr', 'L’utilisateur et les rôles ont été enregistrés.'),
('Benutzerverwaltung', 'de', 'Benutzerverwaltung'),
('Benutzerverwaltung', 'fr', 'Gestion des utilisateurs'),
('Bereits nach Vereinsflieger exportiert, schreibgeschützt.', 'de', 'Bereits nach Vereinsflieger exportiert, schreibgeschützt.'),
('Bereits nach Vereinsflieger exportiert, schreibgeschützt.', 'fr', 'Déjà exporté vers Vereinsflieger, en lecture seule.'),
('bereits vorhanden', 'de', 'bereits vorhanden'),
('bereits vorhanden', 'fr', 'déjà présent'),
('Bereits vorhanden:', 'de', 'Bereits vorhanden:'),
('Bereits vorhanden:', 'fr', 'Déjà présents :'),
('Betriebstag', 'de', 'Betriebstag'),
('Betriebstag', 'fr', 'Journée d’exploitation'),
('Bis', 'de', 'Bis'),
('Bis', 'fr', 'Au'),
('bis', 'de', 'bis'),
('bis', 'fr', 'au'),
('Bis darf nicht vor Von liegen.', 'de', 'Bis darf nicht vor Von liegen.'),
('Bis darf nicht vor Von liegen.', 'fr', 'La date de fin ne peut pas précéder la date de début.'),
('Bitte auswählen', 'de', 'Bitte auswählen'),
('Bitte auswählen', 'fr', 'Veuillez sélectionner'),
('Bitte eine gültige Mailadresse eingeben.', 'de', 'Bitte eine gültige Mailadresse eingeben.'),
('Bitte eine gültige Mailadresse eingeben.', 'fr', 'Veuillez saisir une adresse e-mail valide.'),
('Bitte Von und Bis setzen.', 'de', 'Bitte Von und Bis setzen.'),
('Bitte Von und Bis setzen.', 'fr', 'Veuillez renseigner les dates Du et Au.'),
('Bitte wählen', 'de', 'Bitte wählen'),
('Bitte wählen', 'fr', 'Veuillez sélectionner'),
('closed', 'de', 'closed'),
('closed', 'fr', 'Clôturé'),
('completed', 'de', 'completed'),
('completed', 'fr', 'Terminé'),
('correction_required', 'de', 'correction_required'),
('correction_required', 'fr', 'Correction requise'),
('CSV-Stammdatenimport', 'de', 'CSV-Stammdatenimport'),
('CSV-Stammdatenimport', 'fr', 'Import CSV des données de base'),
('D1-Änderungsliste', 'de', 'D1-Änderungsliste'),
('D1-Änderungsliste', 'fr', 'Liste des modifications D1'),
('Dashboard', 'de', 'Dashboard'),
('Dashboard', 'fr', 'Tableau de bord'),
('Datumsfilter Von/Bis nicht gefunden.', 'de', 'Datumsfilter Von/Bis nicht gefunden.'),
('Datumsfilter Von/Bis nicht gefunden.', 'fr', 'Filtres de date Du/Au introuvables.'),
('Der letzte aktive Administrator kann nicht deaktiviert oder seiner Administratorrolle beraubt werden.', 'de', 'Der letzte aktive Administrator kann nicht deaktiviert oder seiner Administratorrolle beraubt werden.'),
('Der letzte aktive Administrator kann nicht deaktiviert oder seiner Administratorrolle beraubt werden.', 'fr', 'Le dernier administrateur actif ne peut pas être désactivé ni privé de son rôle administrateur.'),
('Details', 'de', 'Details'),
('Details', 'fr', 'Détails'),
('Details:', 'de', 'Details:'),
('Details:', 'fr', 'Détails :'),
('Dienst übernehmen', 'de', 'Dienst übernehmen'),
('Dienst übernehmen', 'fr', 'Prendre le service'),
('Diese Angaben werden für Vereinsflieger und die Rechnungsstellung benötigt. Im Export wird automatisch „Nachname, Vorname“ gebildet.', 'de', 'Diese Angaben werden für Vereinsflieger und die Rechnungsstellung benötigt. Im Export wird automatisch „Nachname, Vorname“ gebildet.'),
('Diese Angaben werden für Vereinsflieger und die Rechnungsstellung benötigt. Im Export wird automatisch „Nachname, Vorname“ gebildet.', 'fr', 'Ces informations sont nécessaires pour Vereinsflieger et la facturation. Lors de l’export, « Nom, prénom » est généré automatiquement.'),
('Eigenstart', 'de', 'Eigenstart'),
('Eigenstart', 'fr', 'Décollage autonome'),
('Eintrag nicht gefunden.', 'de', 'Eintrag nicht gefunden.'),
('Eintrag nicht gefunden.', 'fr', 'Entrée introuvable.'),
('Endpoint ist nicht korrekt installiert.', 'de', 'Endpoint ist nicht korrekt installiert.'),
('Endpoint ist nicht korrekt installiert.', 'fr', 'Le point de terminaison n’est pas correctement installé.'),
('Erfolgreich', 'de', 'Erfolgreich'),
('Erfolgreich', 'fr', 'Réussi'),
('exported', 'de', 'exported'),
('exported', 'fr', 'Exporté'),
('Exportiert', 'de', 'Exportiert'),
('Exportiert', 'fr', 'Exporté'),
('Exportjournal', 'de', 'Exportjournal'),
('Exportjournal', 'fr', 'Journal des exports'),
('Exportvorschau', 'de', 'Exportvorschau'),
('Exportvorschau', 'fr', 'Aperçu de l’export'),
('Externen Pilot / FI erfassen', 'de', 'Externen Pilot / FI erfassen'),
('Externen Pilot / FI erfassen', 'fr', 'Saisir un pilote externe / FI'),
('Externer Kontakt konnte nicht gespeichert werden:', 'de', 'Externer Kontakt konnte nicht gespeichert werden:'),
('Externer Kontakt konnte nicht gespeichert werden:', 'fr', 'Le contact externe n’a pas pu être enregistré :'),
('Externer Pilot / FI', 'de', 'Externer Pilot / FI'),
('Externer Pilot / FI', 'fr', 'Pilote externe / FI'),
('failed', 'de', 'failed'),
('failed', 'fr', 'Échec'),
('Fehlende kTrax-Daten importieren?', 'de', 'Fehlende kTrax-Daten importieren?'),
('Fehlende kTrax-Daten importieren?', 'fr', 'Importer les données kTrax manquantes ?'),
('Fehler', 'de', 'Fehler'),
('Fehler', 'fr', 'Erreur'),
('Fehler:', 'de', 'Fehler:'),
('Fehler:', 'fr', 'Erreurs :'),
('Flug korrigieren', 'de', 'Flug korrigieren'),
('Flug korrigieren', 'fr', 'Corriger le vol'),
('Flug manuell erfassen', 'de', 'Flug manuell erfassen'),
('Flug manuell erfassen', 'fr', 'Saisir un vol manuellement'),
('Flugart', 'de', 'Flugart'),
('Flugart', 'fr', 'Type de vol'),
('Flugbetrieb', 'de', 'Flugbetrieb'),
('Flugbetrieb', 'fr', 'Opérations de vol'),
('Flugdienstleiter', 'de', 'Flugdienstleiter'),
('Flugdienstleiter', 'fr', 'Chef de service de vol'),
('Flugdienstleiter hat den Betriebstag abgeschlossen und für VF freigegeben.', 'de', 'Flugdienstleiter hat den Betriebstag abgeschlossen und für VF freigegeben.'),
('Flugdienstleiter hat den Betriebstag abgeschlossen und für VF freigegeben.', 'fr', 'Le chef de service de vol a clôturé la journée d’exploitation et l’a validée pour VF.'),
('Flugdienstleiterdienst', 'de', 'Flugdienstleiterdienst'),
('Flugdienstleiterdienst', 'fr', 'Service de chef de vol'),
('Flugfreigaben', 'de', 'Flugfreigaben'),
('Flugfreigaben', 'fr', 'Validations des vols'),
('Flugzeit', 'de', 'Flugzeit'),
('Flugzeit', 'fr', 'Durée du vol'),
('Flugzeit:', 'de', 'Flugzeit:'),
('Flugzeit:', 'fr', 'Durée du vol :'),
('Freigabe nicht möglich. Pflichtfelder fehlen oder sind ungültig.', 'de', 'Freigabe nicht möglich. Pflichtfelder fehlen oder sind ungültig.'),
('Freigabe nicht möglich. Pflichtfelder fehlen oder sind ungültig.', 'fr', 'Validation impossible. Des champs obligatoires sont manquants ou non valides.'),
('Freigegeben', 'de', 'Freigegeben'),
('Freigegeben', 'fr', 'Validé'),
('Gestern', 'de', 'Gestern'),
('Gestern', 'fr', 'Hier'),
('glider_flight', 'de', 'glider_flight'),
('glider_flight', 'fr', 'Vol en planeur'),
('glider_tow', 'de', 'glider_tow'),
('glider_tow', 'fr', 'Remorquage planeur'),
('Heute', 'de', 'Heute'),
('Heute', 'fr', 'Aujourd’hui'),
('id fehlt', 'de', 'id fehlt'),
('id fehlt', 'fr', 'id manque'),
('imported', 'de', 'imported'),
('imported', 'fr', 'Importé'),
('Importieren', 'de', 'Importieren'),
('Importieren', 'fr', 'Importer'),
('importiert', 'de', 'importiert'),
('importiert', 'fr', 'importé'),
('in_review', 'de', 'in_review'),
('in_review', 'fr', 'En cours de contrôle'),
('in_sync', 'de', 'in_sync'),
('in_sync', 'fr', 'Synchronisé'),
('Inaktiv', 'de', 'Inaktiv'),
('Inaktiv', 'fr', 'Inactif'),
('Ja', 'de', 'Ja'),
('Ja', 'fr', 'Oui'),
('Kein Flugdienstleiter aktiv', 'de', 'Kein Flugdienstleiter aktiv'),
('Kein Flugdienstleiter aktiv', 'fr', 'Aucun chef de service de vol actif'),
('Kein Motorflug in dieser Operation vorhanden.', 'de', 'Kein Motorflug in dieser Operation vorhanden.'),
('Kein Motorflug in dieser Operation vorhanden.', 'fr', 'Aucun vol moteur dans cette opération.'),
('Kein Motorflug vorhanden.', 'de', 'Kein Motorflug vorhanden.'),
('Kein Motorflug vorhanden.', 'fr', 'Aucun vol moteur disponible.'),
('Kein Motorflug zugeordnet.', 'de', 'Kein Motorflug zugeordnet.'),
('Kein Motorflug zugeordnet.', 'fr', 'Aucun vol moteur associé.'),
('Kein Motorflug/Schlepp vorhanden.', 'de', 'Kein Motorflug/Schlepp vorhanden.'),
('Kein Motorflug/Schlepp vorhanden.', 'fr', 'Aucun vol moteur/remorquage disponible.'),
('Kein Segelflug in dieser Operation vorhanden.', 'de', 'Kein Segelflug in dieser Operation vorhanden.'),
('Kein Segelflug in dieser Operation vorhanden.', 'fr', 'Aucun vol en planeur dans cette opération.'),
('Kein Segelflug vorhanden.', 'de', 'Kein Segelflug vorhanden.'),
('Kein Segelflug vorhanden.', 'fr', 'Aucun vol en planeur disponible.'),
('Kein Segelflug zu diesem Motorflug vorhanden.', 'de', 'Kein Segelflug zu diesem Motorflug vorhanden.'),
('Kein Segelflug zu diesem Motorflug vorhanden.', 'fr', 'Aucun vol en planeur correspondant à ce vol moteur.'),
('Kein Segelflug zugeordnet.', 'de', 'Kein Segelflug zugeordnet.'),
('Kein Segelflug zugeordnet.', 'fr', 'Aucun vol en planeur associé.'),
('Keine', 'de', 'Keine'),
('Keine', 'fr', 'Aucun'),
('Keine Berechtigung.', 'de', 'Keine Berechtigung.'),
('Keine Berechtigung.', 'fr', 'Autorisation insuffisante.'),
('Keine Einträge im aktuellen Filter.', 'de', 'Keine Einträge im aktuellen Filter.'),
('Keine Einträge im aktuellen Filter.', 'fr', 'Aucune entrée dans le filtre actuel.'),
('Keine Flüge mit Korrektur erforderlich.', 'de', 'Keine Flüge mit Korrektur erforderlich.'),
('Keine Flüge mit Korrektur erforderlich.', 'fr', 'Aucun vol nécessitant une correction.'),
('Keine offenen Flüge.', 'de', 'Keine offenen Flüge.'),
('Keine offenen Flüge.', 'fr', 'Aucun vol ouvert.'),
('Keine strukturell unvollständigen Flugoperationen.', 'de', 'Keine strukturell unvollständigen Flugoperationen.'),
('Keine strukturell unvollständigen Flugoperationen.', 'fr', 'Aucune opération de vol structurellement incomplète.'),
('Keine Treffer', 'de', 'Keine Treffer'),
('Keine Treffer', 'fr', 'Aucun résultat'),
('Kommentar', 'de', 'Kommentar'),
('Kommentar', 'fr', 'Commentaire'),
('Kontakt übernehmen', 'de', 'Kontakt übernehmen'),
('Kontakt übernehmen', 'fr', 'Enregistrer le contact'),
('Kontakte', 'de', 'Kontakte'),
('Kontakte', 'fr', 'Contacts'),
('Korrektur', 'de', 'Korrektur'),
('Korrektur', 'fr', 'Correction'),
('Korrektur nötig', 'de', 'Korrektur nötig'),
('Korrektur nötig', 'fr', 'Correction requise'),
('kTrax-Import', 'de', 'kTrax-Import'),
('kTrax-Import', 'fr', 'Import kTrax'),
('kTrax-Import abgeschlossen.', 'de', 'kTrax-Import abgeschlossen.'),
('kTrax-Import abgeschlossen.', 'fr', 'Import kTrax terminé.'),
('kTrax-Import fehlgeschlagen.', 'de', 'kTrax-Import fehlgeschlagen.'),
('kTrax-Import fehlgeschlagen.', 'fr', 'Échec de l’import kTrax.'),
('kTrax-Import läuft...', 'de', 'kTrax-Import läuft...'),
('kTrax-Import läuft...', 'fr', 'Import kTrax en cours…'),
('Laden', 'de', 'Laden'),
('Laden', 'fr', 'Charger'),
('Laden...', 'de', 'Laden...'),
('Laden...', 'fr', 'Chargement…'),
('Landezeit', 'de', 'Landezeit'),
('Landezeit', 'fr', 'Heure d’atterrissage'),
('Landung', 'de', 'Landung'),
('Landung', 'fr', 'Atterrissage'),
('Landung:', 'de', 'Landung:'),
('Landung:', 'fr', 'Atterrissage :'),
('Letzte 7 Tage', 'de', 'Letzte 7 Tage'),
('Letzte 7 Tage', 'fr', '7 derniers jours'),
('local_change_pending', 'de', 'local_change_pending'),
('local_change_pending', 'fr', 'Modification locale en attente'),
('Logout', 'de', 'Logout'),
('Logout', 'fr', 'Se déconnecter'),
('LSZJ Dashboard', 'de', 'LSZJ Dashboard'),
('LSZJ Dashboard', 'fr', 'Tableau de bord LSZJ'),
('Löschen', 'de', 'Löschen'),
('Löschen', 'fr', 'Supprimer'),
('Mailadresse', 'de', 'Mailadresse'),
('Mailadresse', 'fr', 'Adresse e-mail'),
('manual', 'de', 'manual'),
('manual', 'fr', 'Saisie manuelle'),
('Manuelle VF-Synchronisation', 'de', 'Manuelle VF-Synchronisation'),
('Manuelle VF-Synchronisation', 'fr', 'Synchronisation manuelle avec VF'),
('Method not allowed', 'de', 'Method not allowed'),
('Method not allowed', 'fr', 'Méthode non autorisée'),
('Methode nicht erlaubt.', 'de', 'Methode nicht erlaubt.'),
('Methode nicht erlaubt.', 'fr', 'Méthode non autorisée.'),
('Motorflug', 'de', 'Motorflug'),
('Motorflug', 'fr', 'Vol moteur'),
('Motorflug kann nicht erhalten werden: tow_callsign fehlt.', 'de', 'Motorflug kann nicht erhalten werden: tow_callsign fehlt.'),
('Motorflug kann nicht erhalten werden: tow_callsign fehlt.', 'fr', 'Le vol moteur ne peut pas être conservé : tow_callsign manque.'),
('Motorflug löschen', 'de', 'Motorflug löschen'),
('Motorflug löschen', 'fr', 'Supprimer le vol moteur'),
('Motorflugpilot', 'de', 'Motorflugpilot'),
('Motorflugpilot', 'fr', 'Pilote avion'),
('Motorminuten', 'de', 'Motorminuten'),
('Motorminuten', 'fr', 'Minutes moteur'),
('Motorpilot', 'de', 'Motorpilot'),
('Motorpilot', 'fr', 'Pilote avion'),
('Motorzeit', 'de', 'Motorzeit'),
('Motorzeit', 'fr', 'Durée moteur'),
('Nachname', 'de', 'Nachname'),
('Nachname', 'fr', 'Nom'),
('Nachname, Vorname, Mailadresse und Telefon sind Pflichtfelder.', 'de', 'Nachname, Vorname, Mailadresse und Telefon sind Pflichtfelder.'),
('Nachname, Vorname, Mailadresse und Telefon sind Pflichtfelder.', 'fr', 'Le nom, le prénom, l’adresse e-mail et le téléphone sont obligatoires.'),
('Nein', 'de', 'Nein'),
('Nein', 'fr', 'Non'),
('Neu importiert:', 'de', 'Neu importiert:'),
('Neu importiert:', 'fr', 'Nouveaux imports :'),
('Offen', 'de', 'Offen'),
('Offen', 'fr', 'Ouvert'),
('open', 'de', 'open'),
('open', 'fr', 'Ouvert'),
('Operation', 'de', 'Operation'),
('Operation', 'fr', 'Opération'),
('Operation nicht gefunden.', 'de', 'Operation nicht gefunden.'),
('Operation nicht gefunden.', 'fr', 'Opération introuvable.'),
('operation_id fehlt.', 'de', 'operation_id fehlt.'),
('operation_id fehlt.', 'fr', 'operation_id manque.'),
('operation_id oder action fehlt', 'de', 'operation_id oder action fehlt'),
('operation_id oder action fehlt', 'fr', 'operation_id ou action manque'),
('operation_id oder part fehlt.', 'de', 'operation_id oder part fehlt.'),
('operation_id oder part fehlt.', 'fr', 'operation_id ou part manque.'),
('pending', 'de', 'pending'),
('pending', 'fr', 'Ouvert'),
('Personen aus VF synchronisieren', 'de', 'Personen aus VF synchronisieren'),
('Personen aus VF synchronisieren', 'fr', 'Synchroniser les personnes depuis VF'),
('Pilot', 'de', 'Pilot'),
('Pilot', 'fr', 'Pilote'),
('Pilot Motorflug', 'de', 'Pilot Motorflug'),
('Pilot Motorflug', 'fr', 'Pilote avion'),
('Pilot Segelflug', 'de', 'Pilot Segelflug'),
('Pilot Segelflug', 'fr', 'Pilote de planeur'),
('ready_for_export', 'de', 'ready_for_export'),
('ready_for_export', 'fr', 'Prêt pour l’export'),
('reconciliation_required', 'de', 'reconciliation_required'),
('reconciliation_required', 'fr', 'Rapprochement requis'),
('Schlepp', 'de', 'Schlepp'),
('Schlepp', 'fr', 'Remorquage'),
('Schlepp zu Segelflug erfassen', 'de', 'Schlepp zu Segelflug erfassen'),
('Schlepp zu Segelflug erfassen', 'fr', 'Saisir le remorquage pour le vol en planeur'),
('Schlepppilot', 'de', 'Schlepppilot'),
('Schlepppilot', 'fr', 'Pilote remorqueur'),
('Schleppzeit', 'de', 'Schleppzeit'),
('Schleppzeit', 'fr', 'Durée du remorquage'),
('Schleppzeit:', 'de', 'Schleppzeit:'),
('Schleppzeit:', 'fr', 'Durée du remorquage :'),
('Schliessen', 'de', 'Schliessen'),
('Schliessen', 'fr', 'Fermer'),
('Segelflug', 'de', 'Segelflug'),
('Segelflug', 'fr', 'Planeur'),
('Segelflug löschen', 'de', 'Segelflug löschen'),
('Segelflug löschen', 'fr', 'Supprimer le vol en planeur'),
('Segelflug zu Schleppflug erfassen', 'de', 'Segelflug zu Schleppflug erfassen'),
('Segelflug zu Schleppflug erfassen', 'fr', 'Saisir le vol en planeur pour le vol de remorquage'),
('Segelflugpilot', 'de', 'Segelflugpilot'),
('Segelflugpilot', 'fr', 'Pilote de planeur'),
('Segelflugschlepp', 'de', 'Segelflugschlepp'),
('Segelflugschlepp', 'fr', 'Remorquage planeur'),
('Seit', 'de', 'Seit'),
('Seit', 'fr', 'Depuis'),
('self_launch', 'de', 'self_launch'),
('self_launch', 'fr', 'Décollage autonome'),
('skipped', 'de', 'skipped'),
('skipped', 'fr', 'Ignoré'),
('Speichern', 'de', 'Speichern'),
('Speichern', 'fr', 'Enregistrer'),
('Speichern & Freigeben', 'de', 'Speichern & Freigeben'),
('Speichern & Freigeben', 'fr', 'Enregistrer et valider'),
('Start', 'de', 'Start'),
('Start', 'fr', 'Départ'),
('Start:', 'de', 'Start:'),
('Start:', 'fr', 'Départ :'),
('Startzeit', 'de', 'Startzeit'),
('Startzeit', 'fr', 'Heure de départ'),
('Status', 'de', 'Status'),
('Status', 'fr', 'Statut'),
('success', 'de', 'success'),
('success', 'fr', 'Réussi'),
('Suche fehlgeschlagen', 'de', 'Suche fehlgeschlagen'),
('Suche fehlgeschlagen', 'fr', 'Échec de la recherche'),
('Tage geprüft:', 'de', 'Tage geprüft:'),
('Tage geprüft:', 'fr', 'Jours contrôlés :'),
('Tagesabschluss', 'de', 'Tagesabschluss'),
('Tagesabschluss', 'fr', 'Clôture journalière'),
('Tagesabschlussprüfung', 'de', 'Tagesabschlussprüfung'),
('Tagesabschlussprüfung', 'fr', 'Contrôle de clôture journalière'),
('Telefon', 'de', 'Telefon'),
('Telefon', 'fr', 'Téléphone'),
('tow_charge', 'de', 'tow_charge'),
('tow_charge', 'fr', 'Frais de remorquage'),
('towplane_only', 'de', 'towplane_only'),
('towplane_only', 'fr', 'Vol moteur'),
('towplane_own', 'de', 'towplane_own'),
('towplane_own', 'fr', 'Vol moteur'),
('Uhr', 'de', 'Uhr'),
('Uhr', 'fr', 'h'),
('Unbekannte Aktion.', 'de', 'Unbekannte Aktion.'),
('Unbekannte Aktion.', 'fr', 'Action inconnue.'),
('Ungültige Aktion', 'de', 'Ungültige Aktion'),
('Ungültige Aktion', 'fr', 'Action non valide'),
('Ungültige JSON-Daten.', 'de', 'Ungültige JSON-Daten.'),
('Ungültige JSON-Daten.', 'fr', 'Données JSON non valides.'),
('Ungültige oder abgelaufene Anfrage.', 'de', 'Ungültige oder abgelaufene Anfrage.'),
('Ungültige oder abgelaufene Anfrage.', 'fr', 'Requête non valide ou expirée.'),
('Vereinsflieger-CSV Export', 'de', 'Vereinsflieger-CSV Export'),
('Vereinsflieger-CSV Export', 'fr', 'Export CSV Vereinsflieger'),
('Von', 'de', 'Von'),
('Von', 'fr', 'Du'),
('Vorname', 'de', 'Vorname'),
('Vorname', 'fr', 'Prénom'),
('Warnung', 'de', 'Warnung'),
('Warnung', 'fr', 'Avertissement'),
('Weiter', 'de', 'Weiter'),
('Weiter', 'fr', 'Continuer'),
('Zeitraum:', 'de', 'Zeitraum:'),
('Zeitraum:', 'fr', 'Période :'),
('Zurück', 'de', 'Zurück'),
('Zurück', 'fr', 'Retour'),
('Zurück zum Dashboard', 'de', 'Zurück zum Dashboard'),
('Zurück zum Dashboard', 'fr', 'Retour au tableau de bord'),
('Änderungen, Korrekturen und Löschungen sind in der Flugfreigabemaske nicht mehr möglich.', 'de', 'Änderungen, Korrekturen und Löschungen sind in der Flugfreigabemaske nicht mehr möglich.'),
('Änderungen, Korrekturen und Löschungen sind in der Flugfreigabemaske nicht mehr möglich.', 'fr', 'Les modifications, corrections et suppressions ne sont plus possibles dans l’écran de validation des vols.')
ON DUPLICATE KEY UPDATE translation_text = VALUES(translation_text);
