-- Restliche Attribut-, Formular- und Systemtexte, UTF-8-sicher und idempotent.
SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;

INSERT INTO i18n_translations (translation_key, lang, translation_text) VALUES
('QR-Code für die C-Büro-Anmeldung', 'de', 'QR-Code für die C-Büro-Anmeldung'),
('QR-Code für die C-Büro-Anmeldung', 'fr', 'Code QR pour la connexion au PC du bureau C'),
('QR-Code zur Passkey-Ersteinrichtung', 'de', 'QR-Code zur Passkey-Ersteinrichtung'),
('QR-Code zur Passkey-Ersteinrichtung', 'fr', 'Code QR pour la configuration initiale de la clé d’accès'),
('Sprachauswahl', 'de', 'Sprachauswahl'),
('Sprachauswahl', 'fr', 'Choix de la langue'),
('Seit {date} Uhr', 'de', 'Seit {date} Uhr'),
('Seit {date} Uhr', 'fr', 'Depuis le {date}'),
('Alle bekannten Piloten anzeigen', 'de', 'Alle bekannten Piloten anzeigen'),
('Alle bekannten Piloten anzeigen', 'fr', 'Afficher tous les pilotes connus'),
('Bitte wählen', 'de', 'Bitte wählen'),
('Bitte wählen', 'fr', 'Veuillez sélectionner'),
('Start:', 'de', 'Start:'),
('Start:', 'fr', 'Départ :'),
('Landung:', 'de', 'Landung:'),
('Landung:', 'fr', 'Atterrissage :'),
('Flugzeit:', 'de', 'Flugzeit:'),
('Flugzeit:', 'fr', 'Durée du vol :'),
('Schleppzeit:', 'de', 'Schleppzeit:'),
('Schleppzeit:', 'fr', 'Durée du remorquage :'),
('Motorminuten', 'de', 'Motorminuten'),
('Motorminuten', 'fr', 'Minutes moteur'),
('Motorflugpilot', 'de', 'Motorflugpilot'),
('Motorflugpilot', 'fr', 'Pilote avion'),
('Externer Pilot / FI', 'de', 'Externer Pilot / FI'),
('Externer Pilot / FI', 'fr', 'Pilote externe / FI'),
('Externen Pilot / FI erfassen', 'de', 'Externen Pilot / FI erfassen'),
('Externen Pilot / FI erfassen', 'fr', 'Saisir un pilote externe / FI'),
('Keine Treffer', 'de', 'Keine Treffer'),
('Keine Treffer', 'fr', 'Aucun résultat'),
('Suche fehlgeschlagen', 'de', 'Suche fehlgeschlagen'),
('Suche fehlgeschlagen', 'fr', 'Échec de la recherche'),
('Kontakt übernehmen', 'de', 'Kontakt übernehmen'),
('Kontakt übernehmen', 'fr', 'Enregistrer le contact'),
('Bitte eine gültige Mailadresse eingeben.', 'de', 'Bitte eine gültige Mailadresse eingeben.'),
('Bitte eine gültige Mailadresse eingeben.', 'fr', 'Veuillez saisir une adresse e-mail valide.'),
('Nachname, Vorname, Mailadresse und Telefon sind Pflichtfelder.', 'de', 'Nachname, Vorname, Mailadresse und Telefon sind Pflichtfelder.'),
('Nachname, Vorname, Mailadresse und Telefon sind Pflichtfelder.', 'fr', 'Le nom, le prénom, l’adresse e-mail et le téléphone sont obligatoires.'),
('Schleppflugzeug ohne gekoppelten Segelflug - Flugart bitte prüfen', 'de', 'Schleppflugzeug ohne gekoppelten Segelflug - Flugart bitte prüfen'),
('Schleppflugzeug ohne gekoppelten Segelflug - Flugart bitte prüfen', 'fr', 'Avion remorqueur sans vol en planeur associé, veuillez vérifier le type de vol.'),
('Segelflug ohne gekoppelten Schleppflug - Flugart bitte prüfen', 'de', 'Segelflug ohne gekoppelten Schleppflug - Flugart bitte prüfen'),
('Segelflug ohne gekoppelten Schleppflug - Flugart bitte prüfen', 'fr', 'Vol en planeur sans remorquage associé, veuillez vérifier le type de vol.'),
('Manuell erfasster Segelflug', 'de', 'Manuell erfasster Segelflug'),
('Manuell erfasster Segelflug', 'fr', 'Vol en planeur saisi manuellement'),
('Manuell erfasster Motorflug', 'de', 'Manuell erfasster Motorflug'),
('Manuell erfasster Motorflug', 'fr', 'Vol moteur saisi manuellement'),
('Manuell erfasster Schleppanteil', 'de', 'Manuell erfasster Schleppanteil'),
('Manuell erfasster Schleppanteil', 'fr', 'Part de remorquage saisie manuellement'),
('Schleppanteil bitte prüfen', 'de', 'Schleppanteil bitte prüfen'),
('Schleppanteil bitte prüfen', 'fr', 'Veuillez vérifier la part de remorquage'),
('Landezeit Motorflug fehlt', 'de', 'Landezeit Motorflug fehlt'),
('Landezeit Motorflug fehlt', 'fr', 'L’heure d’atterrissage du vol moteur manque'),
('Falsche Zeiten', 'de', 'Falsche Zeiten'),
('Falsche Zeiten', 'fr', 'Horaires incorrects')
ON DUPLICATE KEY UPDATE translation_text = VALUES(translation_text);
