<?php
require __DIR__ . '/db.php';
require __DIR__ . '/helpers.php';
$pdo=db();
$date=$_GET['date']??date('Y-m-d');
$status=$_GET['status']??'pending';
$allowed=['pending','correction_required','approved','exported','all'];
if(!in_array($status,$allowed,true)){json_response(['ok'=>false,'error'=>'Ungueltiger Statusfilter'],400);}
$gliderStatusSql='';$towStatusSql='';$gliderParams=[$date];$towParams=[$date];
if($status!=='all'){$gliderStatusSql=' AND e.approval_status = ?';$towStatusSql=' AND e.approval_status = ?';$gliderParams[]=$status;$towParams[]=$status;}
function count_by_status_for_entries(PDO $pdo,string $date,array $entryTypes):array{$ph=implode(',',array_fill(0,count($entryTypes),'?'));$stmt=$pdo->prepare("SELECT approval_status, COUNT(*) AS cnt FROM accounting_entries WHERE DATE(departure_time)=? AND entry_type IN ($ph) GROUP BY approval_status");$stmt->execute(array_merge([$date],$entryTypes));$out=['pending'=>0,'correction_required'=>0,'approved'=>0,'exported'=>0];foreach($stmt->fetchAll() as $row){$out[$row['approval_status']]=(int)$row['cnt'];}return $out;}
$gliderStmt=$pdo->prepare("SELECT e.id AS accounting_entry_id,e.operation_id,e.entry_type,e.callsign,e.pilot_name,e.attendant_name,e.departure_time,e.departure_location,e.arrival_time,e.arrival_location,e.flight_minutes,e.landing_count,e.start_type,e.charge_mode,cm.name AS charge_mode_name,e.tow_callsign,e.tow_height_m,e.vf_flight_type_id,ft.code AS vf_flight_type_code,ft.name AS vf_flight_type_name,e.comment,e.approval_status,e.approved_by,e.approved_at,e.correction_note,o.glider_pilot_name,o.instructor_name,ts.tow_minutes AS glider_tow_minutes,ts.tow_height_m AS glider_tow_height,ts.tow_callsign AS glider_tow_callsign FROM accounting_entries e JOIN operations o ON o.id=e.operation_id LEFT JOIN tow_segments ts ON ts.operation_id=e.operation_id LEFT JOIN flight_types ft ON ft.id=e.vf_flight_type_id LEFT JOIN charge_modes cm ON cm.id=e.charge_mode WHERE e.entry_type='glider_flight' AND DATE(e.departure_time)=?{$gliderStatusSql} ORDER BY e.departure_time,e.id");
$gliderStmt->execute($gliderParams);$gliderEntries=$gliderStmt->fetchAll();
$towStmt=$pdo->prepare("SELECT e.id AS accounting_entry_id,e.operation_id,e.entry_type,e.callsign,e.tow_callsign,e.tow_pilot_name,e.departure_time,e.departure_location,e.arrival_time,e.arrival_location,e.flight_minutes,e.tow_minutes,e.landing_count,e.start_type,e.charge_mode,cm.name AS charge_mode_name,e.tow_height_m,e.vf_flight_type_id,ft.code AS vf_flight_type_code,ft.name AS vf_flight_type_name,e.comment,e.approval_status,e.approved_by,e.approved_at,e.correction_note,ts.id AS tow_segment_id,ts.glider_callsign,ts.segment_start,ts.segment_end,ts.cost_center,o.kind AS operation_kind FROM accounting_entries e JOIN operations o ON o.id=e.operation_id LEFT JOIN tow_segments ts ON ts.operation_id=e.operation_id LEFT JOIN flight_types ft ON ft.id=e.vf_flight_type_id LEFT JOIN charge_modes cm ON cm.id=e.charge_mode WHERE e.entry_type IN ('tow_charge','towplane_own') AND DATE(e.departure_time)=?{$towStatusSql} ORDER BY e.departure_time,e.id");
$towStmt->execute($towParams);$towItems=$towStmt->fetchAll();
json_response(['ok'=>true,'date'=>$date,'status_filter'=>$status,'counts'=>['glider'=>count_by_status_for_entries($pdo,$date,['glider_flight']),'tow'=>count_by_status_for_entries($pdo,$date,['tow_charge','towplane_own'])],'glider_entries'=>$gliderEntries,'tow_items'=>$towItems,'tow_segments'=>$towItems]);
