<?php
function jinput(): array { return json_decode(file_get_contents('php://input'), true) ?: $_POST; }
function qv(array $a, string $k, $d=null) { return array_key_exists($k,$a) && $a[$k] !== '' ? $a[$k] : $d; }
function dtv(string $date, $time): ?string { return $time ? dt_string($date, $time) : null; }
function mins_v(string $date, $s, $e): ?int { return ($s && $e) ? minutes_between($date, $s, $e) : null; }
function int_null($v): ?int { return ($v === '' || $v === null) ? null : (int)$v; }
function insert_row(PDO $pdo, string $table, array $data): int { $cols=array_keys($data); $sql='INSERT INTO '.$table.' ('.implode(',',$cols).') VALUES (:'.implode(',:',$cols).')'; $stmt=$pdo->prepare($sql); foreach($data as $k=>$v) $stmt->bindValue(':'.$k,$v); $stmt->execute(); return (int)$pdo->lastInsertId(); }
function update_row(PDO $pdo, string $table, array $data, string $where, array $params): void { $sets=[]; foreach($data as $k=>$_)$sets[]=$k.'=:'.$k; $stmt=$pdo->prepare('UPDATE '.$table.' SET '.implode(',',$sets).' WHERE '.$where); foreach($data as $k=>$v)$stmt->bindValue(':'.$k,$v); foreach($params as $k=>$v)$stmt->bindValue(':'.$k,$v); $stmt->execute(); }
function upsert_tow_segment(PDO $pdo, array $data): void { $cols=array_keys($data); $updates=[]; foreach($cols as $c) if($c!=='operation_id') $updates[]=$c.'=VALUES('.$c.')'; $updates[]='updated_at=CURRENT_TIMESTAMP'; $sql='INSERT INTO tow_segments ('.implode(',',$cols).') VALUES (:'.implode(',:',$cols).') ON DUPLICATE KEY UPDATE '.implode(',',$updates); $stmt=$pdo->prepare($sql); foreach($data as $k=>$v)$stmt->bindValue(':'.$k,$v); $stmt->execute(); }
function get_entries(PDO $pdo, int $opId): array { $stmt=$pdo->prepare('SELECT * FROM accounting_entries WHERE operation_id=? ORDER BY FIELD(entry_type,\'glider_flight\',\'tow_charge\',\'towplane_own\'), id'); $stmt->execute([$opId]); $out=['glider'=>null,'tow_charge'=>null,'towplane_own'=>null,'all'=>[]]; foreach($stmt->fetchAll() as $e){$out['all'][]=$e;if($e['entry_type']==='glider_flight')$out['glider']=$e;if($e['entry_type']==='tow_charge')$out['tow_charge']=$e;if($e['entry_type']==='towplane_own')$out['towplane_own']=$e;} return $out; }
function set_pending_operation(PDO $pdo, int $opId): void { $pdo->prepare("UPDATE operations SET approval_status='pending', approved_by=NULL, approved_by_user_id=NULL, approved_at=NULL WHERE id=?")->execute([$opId]); $pdo->prepare("UPDATE accounting_entries SET approval_status='pending', approved_by=NULL, approved_by_user_id=NULL, approved_at=NULL, exported_at=NULL, vf_exported_at=NULL, export_batch=NULL WHERE operation_id=?")->execute([$opId]); $pdo->prepare("UPDATE tow_segments SET approval_status='pending' WHERE operation_id=?")->execute([$opId]); }
?>
